import { useEffect, useRef, useState } from 'react'
import { useTheme } from '../lib/ThemeContext'

// Diagrams come from step content generated by our backend. Inline SVG is
// sanitized server-side (allowlisted shapes/text only — see backend
// sanitize_step_diagrams); mermaid source is rendered client-side with
// securityLevel 'strict'. Both degrade to nothing on any failure.

let mermaidSeq = 0

export function MermaidDiagram({ code }: { code: string }) {
  const { isDark } = useTheme()
  const [svg, setSvg] = useState<string | null>(null)
  const [failed, setFailed] = useState(false)
  const idRef = useRef(`step-mmd-${++mermaidSeq}`)

  useEffect(() => {
    let cancelled = false
    setSvg(null)
    setFailed(false)
    import('mermaid')
      .then(async ({ default: mermaid }) => {
        mermaid.initialize({
          startOnLoad: false,
          securityLevel: 'strict',
          theme: isDark ? 'dark' : 'neutral',
          fontFamily: 'inherit',
        })
        try {
          const { svg: rendered } = await mermaid.render(idRef.current, code)
          if (!cancelled) setSvg(rendered)
        } catch {
          if (!cancelled) setFailed(true)
        }
      })
      .catch(() => { if (!cancelled) setFailed(true) })
    return () => { cancelled = true }
  }, [code, isDark])

  if (failed) return null
  if (!svg) {
    return <div className="h-32 rounded-2xl shimmer-bg" aria-hidden="true" />
  }
  return (
    <div className="rounded-2xl border border-slate-200 dark:border-slate-700/40 bg-white/70 dark:bg-slate-800/25 px-4 py-4 overflow-x-auto">
      <div
        className="[&_svg]:max-w-full [&_svg]:h-auto [&_svg]:mx-auto"
        dangerouslySetInnerHTML={{ __html: svg }}
      />
    </div>
  )
}

export function SvgDiagram({ svg }: { svg: string }) {
  // Generated SVGs assume a light background — keep a white panel in dark mode.
  return (
    <div className="rounded-2xl border border-slate-200 dark:border-slate-700/40 bg-white px-4 py-4 overflow-x-auto">
      <div
        className="[&_svg]:max-w-full [&_svg]:h-auto [&_svg]:mx-auto"
        dangerouslySetInnerHTML={{ __html: svg }}
      />
    </div>
  )
}
